# Generated by Django 3.1.14 on 2022-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=500, null=True)),
                ('pro_image', models.ImageField(upload_to='upload/product/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.category')),
            ],
        ),
    ]
